import type { AssessmentPatternSeed } from '../types';

export const aiPatterns: readonly AssessmentPatternSeed[] = [
  {
    code: 'A-01',
    category: 'ai',
    title: 'LLM をプロダクト機能に組み込む設計判断',
    description: '機能要件に対し、LLM をどう組み込むか（生成、分類、抽出、要約、対話など）を判断し、プロンプト構造・フォールバック・UX を設計した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「LLM をプロダクト機能（生成・分類・抽出・要約・対話など）に組み込む設計を判断した経験はありますか」',
    level_2_focus: '機能内容 / 採用したモデル / プロンプト構造 / フォールバック設計',
    level_3_focus: '「なぜ LLM か、なぜ既存手法でないか」/ 失敗時の UX / プロンプトインジェクション対策',
    level_4_focus: 'BtoC でユーザー数が多ければ / 規制業界なら / レイテンシ要件が厳しければ',
    signals: ['プロンプトの A/B', 'トークン数の見積もり', 'ガードレールの実装', '失敗ログの観察'],
    ai_perspective: '「自分の AI 活用判断」が問い自体になる稀有なパターン → メタな深掘り（自分が使った AI 観の言語化）',
  },
  {
    code: 'A-02',
    category: 'ai',
    title: 'RAG システムの設計判断',
    description: '社内ドキュメント・製品知識・大規模コンテンツに対し、RAG（Retrieval-Augmented Generation）を設計・実装した。チャンク戦略、embedding 選定、検索方式、リランク、評価を含む。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「社内ドキュメント・製品知識・大規模コンテンツに対し、RAG（Retrieval-Augmented Generation）を設計・実装した経験はありますか」',
    level_2_focus: 'コンテンツ / チャンク戦略 / embedding 選定 / 検索方式 / リランク',
    level_3_focus: '「精度が出ない」原因の retrieval / generation / プロンプトの切り分け / 評価データセット',
    level_4_focus: '機密情報を含むなら / コンテンツ更新頻度が高ければ',
    signals: ['チャンクサイズの試行錯誤', 'ハイブリッド検索（BM25 + ベクトル）', 'リランクの効果測定経験'],
    ai_perspective: 'RAG 自体が AI、メタ問い：「retrieval の評価をどう自動化したか」',
  },
  {
    code: 'A-03',
    category: 'ai',
    title: 'AI エージェント設計',
    description: '複数ステップのタスクを実行する AI エージェントを設計・実装した。ツール定義、ループ制御、ガードレール、コスト管理、人間介在点（HITL）を含む。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「複数ステップのタスクを実行する AI エージェント（ツール呼び出し・ループ制御を含む）を設計・実装した経験はありますか」',
    level_2_focus: 'タスク内容 / ツール定義 / ループ制御 / ガードレール / HITL',
    level_3_focus: '自律性の許容範囲 / 失敗時のリカバリ / 人間レビューの差し込み点',
    level_4_focus: 'BtoC でエンドユーザー直結なら / コスト制約が厳しければ',
    signals: ['暴走・無限ループ・コスト爆発の経験談', 'ツール粒度の試行錯誤', '最大ステップ数の設計'],
    ai_perspective: '「エージェントが間違った行動をとる失敗モード」を具体的に語れるか',
  },
  {
    code: 'A-04',
    category: 'ai',
    title: 'LLM API のコスト・レイテンシ・品質トレードオフ',
    description: '本番運用に向けて、LLM API のモデル選定、プロンプトキャッシュ、ストリーミング、バッチ処理、ファインチューニング、SLM 活用などを判断した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「本番運用に向けて、LLM API のモデル選定・キャッシュ・ストリーミング・バッチ・ファインチューニングなどでコスト・レイテンシ・品質を判断した経験はありますか」',
    level_2_focus: 'モデル選定 / 月額コスト / レイテンシ要件 / 品質測定',
    level_3_focus: '大型 vs 小型モデル / API vs 自社ホスティング / リアルタイム vs バッチ',
    level_4_focus: 'スタートアップでコスト制約なら / エンタープライズで品質要求なら',
    signals: ['QPS × トークン数の見積もり', 'プロンプトキャッシュの効果計測', 'モデル切替戦略'],
    ai_perspective: '「コストとモデル選択の判断軸」自体が AI 活用の核心',
  },
  {
    code: 'A-05',
    category: 'ai',
    title: 'AI 機能の評価・改善ループ設計',
    description: 'AI 機能の品質を継続的に評価・改善する仕組みを設計した。オフライン評価データセット、A/B テスト、人手評価、ハルシネーション検出、回帰テストを含む。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「AI 機能の品質を継続的に評価・改善する仕組み（オフライン評価データセット / A/B / 人手評価 / ハルシネーション検出）を設計した経験はありますか」',
    level_2_focus: '評価対象 / 評価データセット / 評価者 / 回帰検出',
    level_3_focus: '「品質」の定義 / 自動評価 vs 人手評価 / 評価コスト',
    level_4_focus: 'ドメインエキスパート評価が必要なら / 多言語対応なら',
    signals: ['golden set のメンテナンス運用', 'LLM as judge の限界認識', '回帰テストの仕組み'],
    ai_perspective: '評価そのものに AI を使うことの是非と限界',
  },
  {
    code: 'A-06',
    category: 'ai',
    title: 'AI ネイティブプロダクトの責務設計',
    description: 'AI を中心機能として据えるプロダクトで、決定論的処理と LLM の責務分担、検証可能性、ユーザーへの説明性、エラー時の責任設計を判断した。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「AI を中心機能として据えるプロダクトで、決定論的処理と LLM の責務分担、検証可能性、ユーザーへの説明性、エラー時の責任設計を判断した経験はありますか」',
    level_2_focus: '責務分担 / 監査ログ設計 / ユーザーへの説明方法',
    level_3_focus: 'ブラックボックスの許容範囲 / 「AI が間違えた時、誰がどう気づくか」の運用設計',
    level_4_focus: 'BtoB エンタープライズなら / 規制業界なら / 法的責任が明確に求められれば',
    signals: ['「人間の最終承認」設計', '信頼度スコアの提示', 'AI 出力のバージョニング'],
    ai_perspective: 'AI を使う側の倫理・責任観そのものが問い',
  },
] as const;
