import type { AssessmentPatternSeed } from '../types';

export const designPatterns: readonly AssessmentPatternSeed[] = [
  {
    code: 'D-01',
    category: 'design',
    title: 'モノリス内の機能の独立サービス化判断',
    description: 'モノリスで動いている機能のうち、1 つが他の数倍のトラフィック・データ量・スケール要件を抱えるようになった。独立サービスとして切り出すか、モノリス内で吸収するかを判断した。',
    expected_scope_min: 3,
    expected_scope_max: 5,
    level_1_intro: '「モノリスの中の特定機能だけがスケール要件で突出し、独立サービスに切り出すか同居で吸収するかを判断した経験はありますか」',
    level_2_focus: '何の機能か / どのスケール要件（QPS, データ量, バッチ時間）か / 結果は分割 or 吸収か / 移行期間と段階',
    level_3_focus: '分割コスト評価（運用、観測、デプロイ）と吸収コスト評価の比較 / 反対意見と撤退条件',
    level_4_focus: 'チーム規模が半分なら / 10 倍トラフィックなら / 今やり直すなら何を変えるか',
    signals: ['境界引きの試行錯誤', '「分割しすぎた / しなさすぎた」の後悔', 'ストラングラーパターンや Anti-Corruption Layer などの言及'],
    ai_perspective: '設計レビューや影響分析で AI を使うとしたら何を任せるか',
  },
  {
    code: 'D-02',
    category: 'design',
    title: '既存スキーマで窮屈になった新要件の取り込み',
    description: '既存の RDB スキーマに収めようとすると無理が出る新要件が来た。テーブル分割、意図的な非正規化、別ストア（NoSQL/検索/時系列）導入のいずれかを選択した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「既存の RDB スキーマに収めようとすると無理が出る新要件で、テーブル分割・非正規化・別ストア導入を判断した経験はありますか」',
    level_2_focus: 'どんな新要件か / どこが窮屈だったか / どの選択肢を採用したか / 移行手順',
    level_3_focus: '「正規化原則」と「現実トレードオフ」の折り合い方 / 別ストア導入時のデュアルライト戦略',
    level_4_focus: 'スタートアップの初期なら / レガシーで触れない部分が多ければ / 今ならどう判断',
    signals: ['スキーマ移行の苦しみ', '整合性ウィンドウの設計', '後悔の具体例'],
    ai_perspective: 'スキーマ設計レビューや差分検出に AI を使う発想があるか',
  },
  {
    code: 'D-03',
    category: 'design',
    title: '同期処理の非同期化・疎結合化',
    description: '外部 API や重い処理に同期で依存している箇所が、サービス全体の可用性・性能の足かせになった。キュー導入、イベント駆動化、キャッシュなどで疎結合化を判断した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「外部 API や重い処理に同期で依存していた箇所を、キュー・イベント駆動・キャッシュなどで疎結合化した経験はありますか」',
    level_2_focus: '何が同期で何が問題だったか / どの方式で疎結合化したか / 整合性ウィンドウ',
    level_3_focus: '同期の単純さを捨てる根拠 / 結果整合で良い領域の見極め / 失敗時の補償設計',
    level_4_focus: '整合性が厳しい業務（決済等）なら / リアルタイム性要求が高ければ',
    signals: ['重複処理対策', 'デッドレターキュー', 'idempotency キーの言及'],
    ai_perspective: '影響分析や test 設計に AI を使う発想',
  },
  {
    code: 'D-04',
    category: 'design',
    title: 'API スタイル選択と後方互換性戦略',
    description: '新規 API、または既存 API の刷新で、REST / gRPC / GraphQL / イベントベース のいずれを選ぶか判断した。バージョニング・後方互換性の戦略も含む。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「新規 API または既存刷新で、REST / gRPC / GraphQL / イベントベース のいずれを選ぶか判断した経験はありますか」',
    level_2_focus: '候補と選定基準 / 後方互換性の保ち方 / バージョニング方式',
    level_3_focus: '「自分が好きな方式」ではなく文脈で選んだ根拠 / 互換破壊時の移行戦略',
    level_4_focus: 'クライアントが社内のみなら / 外部公開なら / 多言語クライアントなら',
    signals: ['deprecation 期間の設計', 'SDK 配布の運用', 'Schema Registry の言及'],
    ai_perspective: 'API 設計の自動化や OpenAPI からのコード生成への AI 活用',
  },
  {
    code: 'D-05',
    category: 'design',
    title: '認証・認可方式の選定／置き換え',
    description: '既存の認証方式（独自セッション、自前 OAuth など）が要件に合わなくなり、IdP 導入・SSO・トークン管理方式の置き換えを判断した。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「既存の認証方式が要件に合わなくなり、IdP 導入・SSO・トークン方式置き換えなどを判断した経験はありますか」',
    level_2_focus: '何が問題で何に変えたか / ユーザー影響の抑え方 / 移行期間の併存設計',
    level_3_focus: '自前運用 vs マネージド / セキュリティ vs UX / 既存トークンの扱い',
    level_4_focus: 'BtoC / BtoB で変わるか / 規模が小さければ自前で十分か',
    signals: ['トークン失効の設計', 'リフレッシュ戦略', 'SCIM や JIT プロビジョニング'],
    ai_perspective: '不審アクセス検知への ML 利用の検討',
  },
  {
    code: 'D-06',
    category: 'design',
    title: 'トランザクション境界と整合性モデル',
    description: '複数のリソースに跨る処理で、ACID トランザクションでまとめるか、結果整合（Saga, Outbox など）で組むかを判断した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「複数リソースに跨る処理で、ACID トランザクション vs 結果整合（Saga, Outbox）を判断した経験はありますか」',
    level_2_focus: 'どんな処理で / どちらを選んだか / 補償処理をどう設計したか',
    level_3_focus: '業務上「ズレてはいけない」「数秒ズレても良い」の見極め根拠',
    level_4_focus: '決済領域なら / オンライン取引でないなら / グローバルマルチリージョンなら',
    signals: ['at-least-once / exactly-once の意味付け', '補償トランザクションの実装経験'],
    ai_perspective: '異常系の検出に AI を使う発想',
  },
  {
    code: 'D-07',
    category: 'design',
    title: 'バッチ vs ストリーミング / push vs pull',
    description: 'データ処理を、バッチで定期実行するか、ストリーミングで継続処理するか、また通知を push で出すか pull で取らせるか判断した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「データ処理をバッチで定期実行するかストリーミングで継続処理するか、push vs pull を判断した経験はありますか」',
    level_2_focus: 'どんなデータ処理か / 何を選んだか / レイテンシ要件',
    level_3_focus: '「ストリーミングの方が新しい」ではない選定根拠 / 運用コストの見積もり',
    level_4_focus: 'データ量が 1/100 なら / 受け手が複数増えるなら',
    signals: ['バックプレッシャー', 'チェックポイント', 'watermark の言及'],
    ai_perspective: '異常検知や品質監視への ML 適用',
  },
  {
    code: 'D-08',
    category: 'design',
    title: 'マルチテナント設計',
    description: 'SaaS 等で複数顧客のデータを扱う際、DB 分離 / スキーマ分離 / 行レベル分離のいずれを選ぶか判断した。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「複数顧客のデータを扱う SaaS で、DB 分離 / スキーマ分離 / 行レベル分離を判断した経験はありますか」',
    level_2_focus: '顧客規模・契約形態 / 選んだ分離方式 / 後から変更したか',
    level_3_focus: '分離強度 vs 運用効率 / 規制要件への対応 / 移行容易性',
    level_4_focus: 'エンタープライズ顧客が増えれば / 海外規制対応なら',
    signals: ['ノイジーネイバー対策', 'テナントごとの障害分離', '暗号鍵の分離設計'],
    ai_perspective: 'テナント間の異常検知やコスト配分への AI 活用',
  },
  {
    code: 'D-09',
    category: 'design',
    title: '共通ライブラリ／プラットフォーム化の判断',
    description: '複数チーム・サービスで似た実装が現れ、共通ライブラリ化・社内プラットフォーム化を判断した。',
    expected_scope_min: 3,
    expected_scope_max: 5,
    level_1_intro: '「複数チーム・サービスで似た実装が現れ、共通ライブラリ化や社内プラットフォーム化を判断した経験はありますか」',
    level_2_focus: '何を共通化したか / どこまで抽象化したか / 浸透・運用体制',
    level_3_focus: '「3 回現れたら共通化」のような自分の基準 / 過剰抽象化の失敗経験',
    level_4_focus: '利用チームが 3 と 30 で違うか / プラットフォームチームを置けないなら',
    signals: ['バージョン管理', '破壊的変更の通知', '利用率モニタリング'],
    ai_perspective: '重複コード検出やライブラリ提案への AI 活用',
  },
  {
    code: 'D-10',
    category: 'design',
    title: 'フロント / バック / BFF の責務分離',
    description: '機能を実装するにあたり、ロジックをフロント / バック / BFF のどこに置くかを判断した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「機能を実装する際、ロジックをフロント / バック / BFF のどこに置くか判断した経験はありますか」',
    level_2_focus: 'どんな機能で / どう分けたか / 後悔した分け方',
    level_3_focus: 'クライアント多様性 / セキュリティ境界 / レイテンシのトレードオフ',
    level_4_focus: 'モバイルが追加されれば / SPA から SSR に変わるなら',
    signals: ['BFF の運用負荷', 'フロント側の状態管理との関係', '認可境界の話'],
    ai_perspective: 'コード生成や型生成での AI 活用観点',
  },
  {
    code: 'D-11',
    category: 'design',
    title: 'ドメインモデルと DB スキーマの距離設計',
    description: 'ドメインモデルと DB スキーマを直結させるか分離するか、ORM をどこまで信頼するかを判断した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「ドメインモデルと DB スキーマの距離をどう設計するか、ORM の使い方を含めて判断した経験はありますか」',
    level_2_focus: '採用した方式（アクティブレコード / リポジトリ / DDD） / 規模と理由',
    level_3_focus: '開発速度 vs 純粋性 / テスト容易性 / 性能透明性',
    level_4_focus: 'チームに DDD 経験者が居なければ / 性能要件が極端なら',
    signals: ['N+1 の罠', 'トランザクションスクリプトとの併用', '複雑性の隔離経験'],
    ai_perspective: 'モデルから DB マイグレーション生成への AI 活用',
  },
  {
    code: 'D-12',
    category: 'design',
    title: '信頼性設計（リトライ・冪等性・タイムアウト・DLQ）',
    description: '外部依存・非同期処理が絡むフローで、リトライ戦略・冪等性キー・タイムアウト・デッドレターキューを設計した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「外部依存・非同期処理で、リトライ・冪等性・タイムアウト・デッドレターキューを設計した経験はありますか」',
    level_2_focus: 'どんなフローで / どう設計したか / 失敗時の処理',
    level_3_focus: 'at-least-once / at-most-once / exactly-once の業務要件への紐づけ / 冪等性キーの設計',
    level_4_focus: '決済なら / 重複が許容できる通知系なら',
    signals: ['ジッタ付き指数バックオフ', 'サーキットブレーカー', 'Outbox パターンの言及'],
    ai_perspective: '異常検知や再送判定への ML 活用',
  },
  {
    code: 'D-13',
    category: 'design',
    title: '新規システムの DB スキーマをゼロから設計',
    description: '新規プロダクト・新機能で、DB スキーマをゼロから設計した。エンティティ抽出、正規化判断、履歴・監査の持ち方、命名規約、拡張性まで含む。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「新規プロダクト・新機能で DB スキーマをゼロから設計した経験はありますか」',
    level_2_focus: 'ドメインの抽出方法 / 履歴・監査・soft delete の方針 / 命名規約',
    level_3_focus: '業務概念の写像精度 / 将来の変化耐性 / 性能 vs 柔軟性',
    level_4_focus: 'スタートアップ初期なら / エンタープライズの基幹系なら / 多言語対応が必要なら',
    signals: ['履歴テーブル設計', 'サロゲートキーと自然キーの選択', 'ER 図のレビュー経験'],
    ai_perspective: '業務ドメインのヒアリングや ER 図ドラフト生成に AI を使う発想',
  },
  {
    code: 'D-14',
    category: 'design',
    title: 'システム全体アーキテクチャをゼロから引く',
    description: '新規プロダクトや大規模刷新で、システム全体のアーキテクチャ（構成図、技術選定、データフロー、デプロイ構成）をゼロから設計し、合意形成・PoC まで持っていった。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「新規プロダクトや大規模刷新で、システム全体のアーキテクチャ（構成図・技術選定・データフロー・デプロイ構成）をゼロから引いた経験はありますか」',
    level_2_focus: '構成図の主要要素 / 技術選定の比較対象 / PoC の有無 / 段階展開計画',
    level_3_focus: 'ビジネス要件の翻訳プロセス / 「最初から完成形」を避ける段階設計 / 合意形成の進め方',
    level_4_focus: 'チーム経験が浅ければ / 5 年後の組織を想定するなら / コスト制約が極端なら',
    signals: ['「他に何を比較したか」が滑らかに出る', 'ADR の運用', 'PoC の合否基準'],
    ai_perspective: 'アーキテクチャ図のドラフトや技術調査に AI を使う／使わない判断',
  },
  {
    code: 'D-15',
    category: 'design',
    title: 'コードベース内部のレイヤー設計・ディレクトリ構成',
    description: 'アプリケーションのレイヤー設計（Clean / Layered / Hexagonal / DDD など）、ディレクトリ構造、パッケージ責務、DI 構造などを設計・改善した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「アプリケーションのレイヤー設計（Clean / Layered / Hexagonal / DDD など）、ディレクトリ構造、パッケージ責務、DI 構造を設計・改善した経験はありますか」',
    level_2_focus: '採用した構造 / 採用根拠 / チーム導入時の摩擦',
    level_3_focus: '「流派の暗唱」を超えた文脈判断 / ここまでやる・やらない の線引き',
    level_4_focus: '5 人チーム / 50 人チームで変わるか / モノリスとマイクロサービスで変わるか',
    signals: ['失敗した抽象化の経験', 'リファクタの段階', 'import 制約の自動化'],
    ai_perspective: 'コード規約のチェックや構造提案への AI 活用',
  },
] as const;
