import type { AssessmentPatternSeed } from '../types';

export const organizationPatterns: readonly AssessmentPatternSeed[] = [
  {
    code: 'O-01',
    category: 'organization',
    title: 'チーム横断の技術選定／合意形成',
    description: '複数チーム・職種にまたがる技術選定で、RFC / ADR / PoC / 設計レビューを通じて合意形成を主導した。',
    expected_scope_min: 3,
    expected_scope_max: 5,
    level_1_intro: '「複数チーム・職種に跨る技術選定で、RFC / ADR / PoC / 設計レビューを通じて合意形成を主導した経験はありますか」',
    level_2_focus: '議題 / 反対意見 / 収束プロセス',
    level_3_focus: '議論の収束タイミング / 反対意見の取り込み / 撤退条件',
    level_4_focus: '経営層が反対なら / リモート分散チームなら',
    signals: ['ADR の運用', 'PoC の合否基準', '反対者の取り込み経験'],
    ai_perspective: '技術調査や論点整理での AI 活用',
  },
  {
    code: 'O-02',
    category: 'organization',
    title: '既存システムの再設計／リプレイス',
    description: '老朽化した既存システムの再設計・リプレイス・撤退を主導した。新規開発ではなく既存資産との戦い。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「老朽化した既存システムの再設計・リプレイス・撤退を主導した経験はありますか」',
    level_2_focus: '対象システム / 採用戦略（全面置換 / 段階移行 / 凍結） / 期間',
    level_3_focus: 'ビジネス継続性との両立 / 旧システム保守チームとの関係',
    level_4_focus: '売上に直結するシステムなら / ベンダーロックインがあれば',
    signals: ['ストラングラーパターン', 'Anti-Corruption Layer', '並行運用の運用負荷経験'],
    ai_perspective: '既存コードベース解析や置き換え提案への AI 活用',
  },
  {
    code: 'O-03',
    category: 'organization',
    title: '開発プロセス導入・改善',
    description: 'CI/CD、コードレビュー、ブランチ戦略、テスト戦略、リリースプロセスなどを導入・改善した。',
    expected_scope_min: 2,
    expected_scope_max: 5,
    level_1_intro: '「CI/CD・コードレビュー・ブランチ戦略・テスト戦略・リリースプロセスを導入・改善した経験はありますか」',
    level_2_focus: '導入対象 / 導入前後の変化 / メトリクス',
    level_3_focus: '厳格さ vs 速度 / チームスキルとの整合 / 形骸化を避ける工夫',
    level_4_focus: '5 人と 50 人で違うか / 規制業界なら',
    signals: ['DORA メトリクス', 'フィーチャーフラグ運用', 'レビュー文化導入の経験'],
    ai_perspective: 'コードレビュー支援や CI 失敗解析への AI 活用',
  },
  {
    code: 'O-04',
    category: 'organization',
    title: 'コーディング規約・設計ガイドラインの策定と浸透',
    description: 'コーディング規約・設計ガイドラインを策定し、チーム全体で守られる状態まで持っていった。',
    expected_scope_min: 5,
    expected_scope_max: 5,
    level_1_intro: '「コーディング規約・設計ガイドラインを策定し、チーム全体で守られる状態まで持っていった経験はありますか」',
    level_2_focus: '策定対象 / 浸透手段 / 違反時の運用',
    level_3_focus: '自動化 vs 人手レビュー / 規約量と現場負荷',
    level_4_focus: '多言語チームなら / 派遣・外注を含むチームなら',
    signals: ['ESLint / 静的解析の組み込み', 'レビュー指摘の傾向分析', '規約の段階導入'],
    ai_perspective: '規約違反検出や自動修正提案への AI 活用',
  },
  {
    code: 'O-05',
    category: 'organization',
    title: 'メンバー育成・オンボーディング設計',
    description: '新メンバーのオンボーディング、ジュニアの育成、シニアのストレッチ機会設計を行った。',
    expected_scope_min: 5,
    expected_scope_max: 5,
    level_1_intro: '「新メンバーのオンボーディング、ジュニア育成、シニアのストレッチ機会設計を行った経験はありますか」',
    level_2_focus: '設計内容 / 期間 / 成果指標',
    level_3_focus: '短期生産性 vs 長期育成 / メンタリングコスト',
    level_4_focus: 'フルリモートなら / 成長速度に差がある複数人なら',
    signals: ['オンボーディングタスクの設計', 'メンタリング時間の確保', '目標設定との連動'],
    ai_perspective: '学習支援やコードレビュー教材生成への AI 活用',
  },
  {
    code: 'O-06',
    category: 'organization',
    title: '採用面接・スキル評価の設計と運用',
    description: '技術面接・コーディング試験・リファレンスチェックなど、自組織の採用プロセス／評価基準を設計・運用した。',
    expected_scope_min: 5,
    expected_scope_max: 5,
    level_1_intro: '「技術面接・コーディング試験・リファレンスチェックなど、自組織の採用プロセス・評価基準を設計・運用した経験はありますか」',
    level_2_focus: '設計対象 / 評価軸 / 運用の歩留まり',
    level_3_focus: '偽陽性 vs 偽陰性のバランス / 候補者体験 / 評価者間の整合',
    level_4_focus: 'スタートアップなら / 大企業の硬直プロセスなら',
    signals: ['落とした人と採った人の振り返り', '評価会議の運用', 'Calibration の経験'],
    ai_perspective: '書類スクリーニングや面接サポートへの AI 活用と倫理',
  },
  {
    code: 'O-07',
    category: 'organization',
    title: '他職種との合意形成・要件折衝',
    description: 'PdM / デザイナー / BizDev / 法務 / 顧客などと、要件の握り・優先度・実現可否の折衝を行った。',
    expected_scope_min: 2,
    expected_scope_max: 4,
    level_1_intro: '「PdM / デザイナー / BizDev / 法務 / 顧客と、要件の握り・優先度・実現可否の折衝を行った経験はありますか」',
    level_2_focus: '折衝相手 / 論点 / 結果',
    level_3_focus: '技術的制約の翻訳 / 妥協点と譲れない線',
    level_4_focus: '受託開発文脈なら / 経営直轄案件なら',
    signals: ['段階案・条件付き案・代替案を出した経験', '見積もり根拠の説明'],
    ai_perspective: '要件整理や仕様ドラフトでの AI 活用',
  },
  {
    code: 'O-08',
    category: 'organization',
    title: '障害対応文化の運用設計',
    description: 'オンコール体制、ポストモーテム文化、SLO / エラーバジェット運用、Game Day などの組織的な仕組みを設計・運用した。',
    expected_scope_min: 5,
    expected_scope_max: 5,
    level_1_intro: '「オンコール体制、ポストモーテム文化、SLO / エラーバジェット運用、Game Day などの組織的仕組みを設計・運用した経験はありますか」',
    level_2_focus: '導入対象 / 運用の歩留まり / 文化の定着度',
    level_3_focus: '組織負荷 vs 信頼性 / 個人ヒロイズムからの脱却',
    level_4_focus: '24/7 でないサービスなら / SRE 不在のチームなら',
    signals: ['オンコール手当', 'ローテーション設計', 'blameless ポストモーテムの経験'],
    ai_perspective: '障害分析支援や類似事例検索への AI 活用',
  },
] as const;
