import type { AssessmentPatternSeed } from '../types';

export const performancePatterns: readonly AssessmentPatternSeed[] = [
  {
    code: 'P-01',
    category: 'performance',
    title: '想定外のトラフィック増によるボトルネック特定',
    description: '急なアクセス増（キャンペーン、SNS バズ、流入経路追加など）で性能問題が顕在化し、ボトルネックを特定して対処した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「急なアクセス増で性能問題が顕在化し、ボトルネックを特定して対処した経験はありますか」',
    level_2_focus: '増加幅（QPS）/ 最初に見た指標 / ボトルネックの位置 / 対処',
    level_3_focus: 'アプリ / DB / NW / FE のどこから攻めたか、なぜか / 暫定と恒久の分離',
    level_4_focus: '自動スケールが整っていれば / コスト制約が厳しければ',
    signals: ['飽和指標の知識（コネクションプール、CPU、I/O）', 'サチった層の特定経験'],
    ai_perspective: '異常検知や負荷予測への AI 活用',
  },
  {
    code: 'P-02',
    category: 'performance',
    title: 'クエリ性能最適化',
    description: 'クエリ性能（N+1、フルスキャン、JOIN 過多、不適切なインデックス）の問題を発見し、最適化した。',
    expected_scope_min: 2,
    expected_scope_max: 2,
    level_1_intro: '「N+1 / フルスキャン / JOIN 過多 / 不適切インデックスなどのクエリ性能問題を発見し最適化した経験はありますか」',
    level_2_focus: '発見経緯 / 実行計画の読み方 / 改善前後の数値',
    level_3_focus: 'クエリ書き換え vs インデックス追加 vs スキーマ変更 vs キャッシュ追加 の選択',
    level_4_focus: '書込が多いシステムなら / レポート系の集計クエリなら',
    signals: ['EXPLAIN 出力の読解', 'Covering Index', 'partial index', '書き込み副作用の言及'],
    ai_perspective: 'スロークエリ自動分析や最適化提案への AI 活用',
  },
  {
    code: 'P-03',
    category: 'performance',
    title: 'キャッシュ戦略の設計と落とし穴',
    description: '多層キャッシュ（CDN / リバースプロキシ / アプリ内 / Redis / DB レベル）の設計や改善を行った。キャッシュ汚染、スタンピード、整合性の問題への対処を含む。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「多層キャッシュ（CDN / リバースプロキシ / アプリ内 / Redis / DB レベル）の設計や改善で、汚染・スタンピード・整合性問題に対処した経験はありますか」',
    level_2_focus: '採用した層 / TTL / 無効化方式 / 直面した問題',
    level_3_focus: '鮮度 vs 性能 / 整合性の妥協点 / stampede 対策',
    level_4_focus: 'BtoC で個別化が強ければ / マスタデータが変わりにくいなら',
    signals: ['cache stampede 対策（lock、jitter、refresh-ahead）', '無効化の困難さの実体験'],
    ai_perspective: 'キャッシュ効率の予測や TTL 最適化への AI 活用',
  },
  {
    code: 'P-04',
    category: 'performance',
    title: '大量データ処理の設計',
    description: 'バッチ・ETL・大規模エクスポート・集計など、大量データを扱う処理を設計し、性能・コスト・運用負荷を成立させた。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「バッチ・ETL・大規模エクスポート・集計など、大量データ処理を設計・性能チューニングした経験はありますか」',
    level_2_focus: 'データ量 / 処理時間 / 並列度 / 採用したフレームワーク',
    level_3_focus: '並列度の決め方 / バックプレッシャー設計 / 再実行性の確保',
    level_4_focus: 'ストリーミングに置き換えるとしたら / クラウドコスト最適化なら',
    signals: ['チェックポイント', 'idempotency', 'メモリ vs ストレージの切り替え経験'],
    ai_perspective: 'データ品質チェックや異常検知への AI 活用',
  },
  {
    code: 'P-05',
    category: 'performance',
    title: 'スケーリング判断',
    description: '水平 / 垂直スケール、シャーディング、Read Replica、リーダー選出など、スケーリングの方式を判断・実装した。',
    expected_scope_min: 3,
    expected_scope_max: 3,
    level_1_intro: '「水平 / 垂直スケール、シャーディング、Read Replica などのスケーリング方式を判断・実装した経験はありますか」',
    level_2_focus: '採用した方式 / シャードキー / リーダー選出 / 移行手順',
    level_3_focus: 'スケール限界の見積もり / 運用複雑性の評価',
    level_4_focus: 'ステートレスにできない部分があれば / マルチリージョンなら',
    signals: ['ステートフル成分の取扱い', 'シャードキー選定の根拠', 'Hot Spot 対策'],
    ai_perspective: '負荷予測やリソース配分への AI 活用',
  },
  {
    code: 'P-06',
    category: 'performance',
    title: '負荷試験の設計と結果反映',
    description: '負荷試験を設計・実施し、結果から設計・実装を変更した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「負荷試験を設計・実施し、結果から設計・実装を変更した経験はありますか」',
    level_2_focus: 'シナリオ / ツール / 想定負荷 / 結果',
    level_3_focus: 'シナリオの作り方 / 本番との乖離許容 / 設計変更の判断',
    level_4_focus: '本番に近いステージング環境がなければ / コストが厳しければ',
    signals: ['ウォームアップ', 'Think Time', 'リアルなトラフィック特性の再現経験'],
    ai_perspective: 'シナリオ生成や結果分析への AI 活用',
  },
  {
    code: 'P-07',
    category: 'performance',
    title: '容量計画と非機能要件',
    description: 'ピーク QPS、ストレージ増加、レイテンシ目標、可用性目標などを定義・見積もりし、設計に反映した。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「ピーク QPS / ストレージ / レイテンシ / 可用性などの非機能要件を定義・見積もりし、設計に反映した経験はありますか」',
    level_2_focus: '見積もり手法 / SLO の定め方 / 設計反映',
    level_3_focus: '過剰投資 vs 過少設計 / フェルミ推定の精度',
    level_4_focus: '規模が一桁違えば / SLO が厳しい業界なら',
    signals: ['エラーバジェット運用', '容量モデル化', 'ピーク係数の見積もり'],
    ai_perspective: '容量予測や SLO 違反予測への AI 活用',
  },
  {
    code: 'P-08',
    category: 'performance',
    title: '裾野レイテンシ（p99 / p999）の改善',
    description: '平均レイテンシは問題ないが、p99 / p999 で問題が出る、テールが太い問題を特定・改善した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「平均は問題なく、p99 / p999 が悪い／テールが太い問題を特定・改善した経験はありますか」',
    level_2_focus: '検知 / 真因切り分け / 改善手法',
    level_3_focus: 'GC / コンテンディション / 外部依存 / cold start の判別',
    level_4_focus: 'ユーザー体験への影響度が違えば / コストが許容できなければ',
    signals: ['ヘッジリクエスト', 'tail-latency cutoff', 'p99 ベースの SLO'],
    ai_perspective: '遅延要因の自動分類への AI 活用',
  },
] as const;
