import type { AssessmentPatternSeed } from '../types';

export const securityPatterns: readonly AssessmentPatternSeed[] = [
  {
    code: 'S-01',
    category: 'security',
    title: '脆弱性／インシデント発生時の優先度判定と対応',
    description: '自社 / 依存ライブラリ / 外部報告などで脆弱性・インシデントが顕在化し、優先度判定 → 修正 → 開示判断を行った。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「脆弱性・インシデントが顕在化し、優先度判定 → 修正 → 開示判断を行った経験はありますか」',
    level_2_focus: '検知経路 / 影響範囲 / 修正と公表のタイミング',
    level_3_focus: 'CVSS だけで動かず自社文脈で再評価する判断 / ステークホルダー対応',
    level_4_focus: '規模が大きければ / 上場企業なら',
    signals: ['CVE 採番', '開示日程の調整', '第三者報告者対応'],
    ai_perspective: '脆弱性影響範囲のコード解析への AI 活用',
  },
  {
    code: 'S-02',
    category: 'security',
    title: '第三者脆弱性診断結果への対応',
    description: '外部の脆弱性診断・ペネトレーションテスト結果に対し、優先度・コスト・影響を踏まえて対応計画を立てた。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「外部の脆弱性診断・ペネトレーションテスト結果に対し、優先度・コスト・影響を踏まえて対応した経験はありますか」',
    level_2_focus: '診断種別 / 指摘件数 / 対応・受容の振り分け',
    level_3_focus: '「全部直す」 vs 「やらない理由を経営に上げる」の判断 / 残留リスクの言語化',
    level_4_focus: '規制業界なら / SaaS で外部公開のみなら',
    signals: ['診断結果のトリアージ表', '再テストの運用', 'SOC レポート作成経験'],
    ai_perspective: '静的解析・SAST/DAST 結果のトリアージ AI 活用',
  },
  {
    code: 'S-03',
    category: 'security',
    title: '個人情報・機密情報の取扱い設計',
    description: '個人情報、機微情報、決済情報などを扱うシステムで、保存・参照・削除・監査の設計を行った。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「個人情報や機微情報を扱うシステムで、保存・参照・削除・監査の設計を行った経験はありますか」',
    level_2_focus: '対象データ / 暗号化粒度 / 削除権設計 / 監査ログ',
    level_3_focus: '法務・コンプラとの折衝 / 最小権限と利便性の妥協点',
    level_4_focus: 'GDPR / PCI-DSS / 医療情報なら',
    signals: ['個人情報保護法の解釈', '削除リクエスト処理', 'PII の DB 分離設計'],
    ai_perspective: '個人情報検出やマスキングへの AI 活用',
  },
  {
    code: 'S-04',
    category: 'security',
    title: 'クレデンシャル管理',
    description: 'パスワード・API キー・証明書などのクレデンシャルを、漏洩防止・ローテーション・KMS / Secrets Manager で安全に運用した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「パスワード・API キー・証明書を、漏洩防止・ローテーション・KMS / Secrets Manager で運用した経験はありますか」',
    level_2_focus: '管理対象 / ローテーション周期 / 漏洩経験',
    level_3_focus: '利便性 vs 安全性 / 自動化レベル',
    level_4_focus: 'スタートアップで人手運用なら / マルチクラウドなら',
    signals: ['漏洩対応の経験', '`.env` を git に上げた事故', 'IAM ロールでの代替設計'],
    ai_perspective: 'コードリポジトリのクレデンシャルスキャンへの AI 活用',
  },
  {
    code: 'S-05',
    category: 'security',
    title: 'アクセス制御の漏れ／権限設計の改善',
    description: '権限境界の漏れ、過剰権限、運用と設計の乖離が見つかり、RBAC / ABAC / PBAC で設計を見直した。',
    expected_scope_min: 3,
    expected_scope_max: 5,
    level_1_intro: '「権限境界の漏れ・過剰権限・運用と設計の乖離が見つかり、RBAC / ABAC / PBAC で設計を見直した経験はありますか」',
    level_2_focus: '発見経緯 / 採用したモデル / 既存運用との折り合い',
    level_3_focus: 'モデルの強さ vs 運用容易性 / ロール爆発への対処',
    level_4_focus: 'B2B SaaS の管理者権限委譲が必要なら / 監査要件が強ければ',
    signals: ['ロールマトリクスの保守', '権限変更フロー', '横展開時の影響範囲経験'],
    ai_perspective: '権限ポリシーのレビューや異常権限検知への AI 活用',
  },
  {
    code: 'S-06',
    category: 'security',
    title: 'コンプライアンス対応',
    description: 'GDPR / PCI-DSS / ISMS / SOC2 / 業界規制などの要件をシステム設計・運用に反映した。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「GDPR / PCI-DSS / ISMS / SOC2 などの要件をシステム設計・運用に反映した経験はありますか」',
    level_2_focus: '対象規格 / 影響を受けた設計 / 監査対応',
    level_3_focus: '規制要件 vs プロダクト体験 / 監査エビデンス収集の自動化',
    level_4_focus: '監査チームが無いなら / 海外展開時に新規制が増えれば',
    signals: ['統制（control）の設計', 'エビデンス収集', '外部監査人とのやり取り'],
    ai_perspective: '監査ログ整理や統制チェックへの AI 活用',
  },
  {
    code: 'S-07',
    category: 'security',
    title: '本番影響を抑えたデータ移行・スキーマ変更',
    description: '本番運用中のシステムで、ダウンタイムを最小化しながらデータ移行・スキーマ変更を実施した。',
    expected_scope_min: 3,
    expected_scope_max: 3,
    level_1_intro: '「本番運用中のシステムで、ダウンタイム最小化しながらデータ移行・スキーマ変更を実施した経験はありますか」',
    level_2_focus: '規模 / 採用した手法 / リハーサル / 切替判断',
    level_3_focus: 'shadow write / dual read / online migration / backfill の設計',
    level_4_focus: 'ダウンタイム許容なら / グローバルマルチリージョンなら',
    signals: ['並行運用期間', 'データ整合性チェック', '切替失敗時のロールバック計画'],
    ai_perspective: '整合性チェックスクリプト生成への AI 活用',
  },
  {
    code: 'S-08',
    category: 'security',
    title: 'バックアップ・リストア・DR の設計と訓練',
    description: 'バックアップ取得だけでなく、リストア手順・DR 訓練まで設計・運用した。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「バックアップ取得だけでなく、リストア手順・DR 訓練まで設計・運用した経験はありますか」',
    level_2_focus: 'RPO / RTO / 訓練頻度 / 実際にリストアした経験',
    level_3_focus: '訓練の運用設計 / コスト vs 安心',
    level_4_focus: '規制業界なら / マルチリージョン要件なら',
    signals: ['「バックアップは取れているがリストアできない」の事故経験', '訓練の文化化'],
    ai_perspective: '訓練シナリオ生成や監査エビデンス整理への AI 活用',
  },
] as const;
