import type { AssessmentPatternSeed } from '../types';

export const troublePatterns: readonly AssessmentPatternSeed[] = [
  {
    code: 'T-01',
    category: 'trouble',
    title: '原因不明の本番障害の一次対応',
    description: '本番サービスで原因不明の障害が発生し、ログ・メトリクス・トレースから症状を切り分け、暫定対応・復旧判断を行った。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「本番サービスで原因不明の障害が起き、ログ・メトリクス・トレースから症状を切り分け、暫定対応・復旧判断を行った経験はありますか」',
    level_2_focus: '検知の経路 / 最初に見た情報 / 仮説の順序 / 暫定対応の選択',
    level_3_focus: '原因究明 vs 復旧優先 の判断 / 暫定対応の副作用評価',
    level_4_focus: '一人体制の障害なら / 規模が 100 倍なら / 真夜中の発生なら',
    signals: ['「最初に見たもの」と「捨てた仮説」が具体的', 'ロールバック判断の語り'],
    ai_perspective: 'ログ要約や仮説生成に AI を使う発想',
  },
  {
    code: 'T-02',
    category: 'trouble',
    title: 'メモリリーク／スレッドリークによる徐々の劣化',
    description: '一定時間運用後にレスポンスが劣化する／OOM で再起動するなど、徐々に進行する劣化型障害を特定・対処した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「一定時間運用後にレスポンスが劣化する／OOM で再起動するなど、徐々に進む劣化型障害を特定・対処した経験はありますか」',
    level_2_focus: '症状の発見経緯 / 使った観測手段（ヒープダンプ等） / 真因',
    level_3_focus: '再起動運用 vs 真因対処 の判断 / GC ログの読み方',
    level_4_focus: '言語ランタイムが違えば / メモリ制約の厳しい組み込みなら',
    signals: ['ヒープダンプの解析', '参照グラフの追跡', '特定オブジェクトの肥大経験'],
    ai_perspective: 'ヒープダンプ解析やパターン特定に AI を使う発想',
  },
  {
    code: 'T-03',
    category: 'trouble',
    title: '外部依存先の障害による波及',
    description: '外部 API / SaaS / クラウドサービスの障害により、自社サービスが波及障害を起こした。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「外部 API・SaaS・クラウドサービスの障害で、自社サービスが波及障害を起こした経験はありますか」',
    level_2_focus: '依存先 / 影響範囲 / 切り離し手段 / 復旧後の対策',
    level_3_focus: '依存先 SLA を超えた信頼性を出す判断 / fallback の実装方針',
    level_4_focus: '依存先が複数あれば / コア依存が 1 つしかないなら',
    signals: ['サーキットブレーカー', 'bulkhead', 'graceful degradation の実装経験'],
    ai_perspective: '外部状態の予測や監視に AI を使う発想',
  },
  {
    code: 'T-04',
    category: 'trouble',
    title: '部分的に遅い／失敗するという症状の絞り込み',
    description: '一部のユーザー / 一部のリクエスト / 特定時間帯だけ遅い・失敗するという症状から、再現条件を絞り込み原因に到達した。',
    expected_scope_min: 1,
    expected_scope_max: 2,
    level_1_intro: '「一部のユーザー・リクエスト・時間帯だけ遅い／失敗する症状から、再現条件を絞り込んで原因に到達した経験はありますか」',
    level_2_focus: '症状の差別化（誰が / どこで / いつ） / 切り分けに使った手段 / 真因',
    level_3_focus: '平均で見ない判断 / 再現困難に対する戦略',
    level_4_focus: 'ユーザー数が少なければ / リアルタイム性が低ければ',
    signals: ['特定 IP / 特定経路 / 特定 SKU など', '絞り込みの具体性'],
    ai_perspective: 'ログクラスタリングや異常パターン抽出への AI 活用',
  },
  {
    code: 'T-05',
    category: 'trouble',
    title: '真因がインフラ層にあった障害',
    description: 'アプリケーション層で原因が見つからず、ネットワーク・DNS・証明書・IAM・k8s リソースなどに真因があった障害を解決した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「アプリ層で原因が見つからず、ネットワーク・DNS・証明書・IAM・k8s リソースなどに真因があった障害を解決した経験はありますか」',
    level_2_focus: 'アプリ層調査の見切り判断 / 切り替えた観測手段 / 連携した役割',
    level_3_focus: 'アプリ vs インフラの境界判断 / インフラ層での仮説順序',
    level_4_focus: 'SRE が居れば / 自分しか居なければ',
    signals: ['tcpdump / dig / 証明書チェーン / cgroup / OOM Killer などの実体験'],
    ai_perspective: 'ログから NW 層問題を推測する AI 補助の可能性',
  },
  {
    code: 'T-06',
    category: 'trouble',
    title: '並行処理特有のバグ',
    description: '競合状態（race condition）、デッドロック、メモリ可視性、リオーダといった並行処理特有のバグを調査・修正した。',
    expected_scope_min: 2,
    expected_scope_max: 2,
    level_1_intro: '「競合状態・デッドロック・メモリ可視性などの並行処理特有のバグを調査・修正した経験はありますか」',
    level_2_focus: 'バグの再現条件 / 観測手段 / 修正方針',
    level_3_focus: '同期プリミティブの選択理由 / 「たまたま動いている」コードの見極め',
    level_4_focus: '言語が変われば（Go の channel vs Java の Lock） / 高並行度なら',
    signals: ['ストレステスト', 'TLA+ や形式検証の言及', 'ハッピーパスでは見えない経験談'],
    ai_perspective: '並行処理バグのレビュー支援への AI 活用',
  },
  {
    code: 'T-07',
    category: 'trouble',
    title: 'データ不整合・破損の復旧',
    description: 'バグ・障害・運用ミスによりデータ不整合・破損が発生し、復旧と原因究明を並行で進めた。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「バグ・障害・運用ミスでデータ不整合・破損が起き、復旧と原因究明を並行で進めた経験はありますか」',
    level_2_focus: '影響範囲特定の SQL / 復旧手順 / 顧客通知判断',
    level_3_focus: '復旧優先度 / バックアップ前提の検証 / 監査ログの存在',
    level_4_focus: '規制業界なら / 影響件数が 100 倍なら',
    signals: ['dry-run', '二重チェック', '監査ログ突合の手順'],
    ai_perspective: '影響範囲特定や復旧クエリ生成への AI 活用',
  },
  {
    code: 'T-08',
    category: 'trouble',
    title: '障害時のステークホルダー対応',
    description: '障害発生時に経営・CS・他チーム・ユーザーに対し、状況・影響・復旧見込みを伝え、判断を仰いだ。',
    expected_scope_min: 4,
    expected_scope_max: 5,
    level_1_intro: '「障害発生時に経営・CS・他チーム・ユーザーに対し、状況・影響・復旧見込みを伝え、判断を仰いだ経験はありますか」',
    level_2_focus: '誰に / いつ / 何を伝えたか / 開示判断',
    level_3_focus: '復旧確度の伝え方 / 補償判断 / 技術的事実と組織的伝え方の翻訳',
    level_4_focus: '上場企業なら / BtoB 大口顧客 1 社が影響なら',
    signals: ['テンプレ・チャネル・更新頻度などの運用設計', '過剰約束を避ける言葉選び'],
    ai_perspective: '障害文面の自動生成への AI 活用と、その限界',
  },
  {
    code: 'T-09',
    category: 'trouble',
    title: 'ポストモーテムと再発防止',
    description: '障害後にポストモーテムを書き、再発防止策を実装まで持っていった。または、ポストモーテム文化自体の導入・改善を行った。',
    expected_scope_min: 2,
    expected_scope_max: 5,
    level_1_intro: '「障害後にポストモーテムを書き、再発防止策を実装まで持っていった経験、または文化導入の経験はありますか」',
    level_2_focus: '書式 / レビュー体制 / アクション実装率',
    level_3_focus: '個人の責任追及 vs システム改善のバランス / 投資コストとリスクの天秤',
    level_4_focus: '受託開発文脈なら / 規制業界の事故対応なら',
    signals: ['blameless の実践', 'Action Item のフォロー運用', '5 Whys / Fishbone などの分析手法'],
    ai_perspective: 'ポストモーテムドラフト生成や類似事故検索に AI を使う発想',
  },
  {
    code: 'T-10',
    category: 'trouble',
    title: '観測性の不足を認識した投資判断',
    description: 'ある障害をきっかけに、メトリクス・ログ・分散トレースが足りていないと判断し、観測性を上げる投資をした。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「ある障害をきっかけに、メトリクス・ログ・分散トレースが足りないと判断し、観測性を上げる投資をした経験はありますか」',
    level_2_focus: '投資前のギャップ / 投資内容 / 効果計測',
    level_3_focus: '投資コスト vs 次の障害コスト / どこを優先したか',
    level_4_focus: 'SRE 体制が無いチームなら / マイクロサービス数が 100 を超えれば',
    signals: ['SLI/SLO 設計', 'ログの構造化', 'トレース ID 伝播の徹底経験'],
    ai_perspective: '異常検知ルール生成、ログクラスタリングへの AI 活用',
  },
  {
    code: 'T-11',
    category: 'trouble',
    title: '移行・リリース後の不具合と前進・撤退判断',
    description: '大きな移行・リリース後に不具合が顕在化し、ロールバック / 前進修正 / 部分有効化を判断した。',
    expected_scope_min: 3,
    expected_scope_max: 4,
    level_1_intro: '「大きな移行やリリース後に不具合が顕在化し、ロールバック / 前進修正 / 部分有効化を判断した経験はありますか」',
    level_2_focus: 'リリース内容 / 不具合の検知 / 判断の選択肢と決め手',
    level_3_focus: '可逆性の見極め / データ移行を伴う場合の不可逆性',
    level_4_focus: 'feature flag の有無で変わるか / リリース時間帯が違えば',
    signals: ['「ロールバックできない移行を作らない」事前設計', 'blue-green / canary の運用'],
    ai_perspective: 'リリース後の異常検知や影響予測への AI 活用',
  },
  {
    code: 'T-12',
    category: 'trouble',
    title: '「再現できないバグ」の取り扱い',
    description: '限られたユーザーからの報告のみで、社内では再現できないバグに対応した。',
    expected_scope_min: 2,
    expected_scope_max: 3,
    level_1_intro: '「限られたユーザーからの報告のみで、社内で再現できないバグに対応した経験はありますか」',
    level_2_focus: 'ユーザーから取った情報 / 追加した観測 / 真因に至った経路',
    level_3_focus: '限定ログ取得 / A/B 出し分け / 静観 の選択基準',
    level_4_focus: 'BtoC でユーザー数が大きければ / BtoB で報告者が VIP なら',
    signals: ['ユーザーのブラウザ・端末・経路情報', '限定有効化フラグの設計経験'],
    ai_perspective: 'ユーザー報告のクラスタリングやセッション再現での AI 活用',
  },
] as const;
